DROP TABLE IF EXISTS user_entity;

CREATE TABLE user_entity (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  username VARCHAR(8) NOT NULL UNIQUE,
  password VARCHAR(16) NOT NULL,
  last_accessed_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
);

insert into user_entity(username, password) values('jordan', 'password');
